name: Set Up Project
on: 
  workflow_call:
jobs:
  Get_Code:
    runs-on: ubuntu-latest
    steps:
     - name: Get Code
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v5
       with:
          node-version: "22"

     - name: Cache dependencies
       id: cache
       uses: actions/cache@v4
       with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

     - name: Install dependencies
       if: steps.cache.outputs.cache-hit != 'true'
       run: npm ci
